### Stage 1: Build the React application
# Use the official Node.js image as the base image
FROM node:16-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --force

# Copy the rest of the application code to the working directory
COPY . .

# Build the React application
RUN npm run build 

### Stage 2: Serve the React application with Nginx
# Use a lightweight web server to serve the React app
FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]